// iss14: EstacaoPirata playing cards (ported from Goob-Station)
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._EstacaoPirata.Cards.Card;
using Content.Shared._EstacaoPirata.Cards.Stack;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._EstacaoPirata.Cards.Hand.UI;

/// <summary>
/// Radial menu listing every card in a hand so the player can pick one to draw.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CardHandMenu : RadialMenu
{
    [Dependency] private IEntityManager _entManager = default!;

    public event Action<NetEntity>? CardHandDrawMessageAction;

    public CardHandMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    // iss14: split out of the constructor so the BUI can use CreateWindow<T>()
    public void SetEntity(EntityUid owner)
    {
        if (!_entManager.TryGetComponent<CardStackComponent>(owner, out var stack))
            return;

        foreach (var card in stack.Cards)
        {
            if (!_entManager.TryGetComponent<CardComponent>(card, out var cardComp))
                return;

            string cardName;
            if (cardComp.Flipped && _entManager.TryGetComponent<MetaDataComponent>(card, out var metadata))
            {
                cardName = metadata.EntityName;
            }
            else
            {
                cardName = Loc.GetString(cardComp.Name);
            }

            var button = new CardMenuButton()
            {
                SetSize = new Vector2(64f, 64f),
                ToolTip = cardName,
            };

            if (_entManager.TryGetComponent<SpriteComponent>(card, out var sprite))
            {
                if (sprite.Icon == null)
                    continue;

                var tex = new TextureRect()
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Texture = sprite.Icon?.Default,
                    TextureScale = new Vector2(2f, 2f),
                };

                button.AddChild(tex);
            }

            Main.AddChild(button);

            button.OnButtonUp += _ =>
            {
                CardHandDrawMessageAction?.Invoke(_entManager.GetNetEntity(card));
                Close();
            };
        }
    }
}

public sealed class CardMenuButton : RadialMenuButtonWithSector
{
}
