using Content.Client.Gifs.UI;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.RichText;
using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Shared.Chat;
using Content.Shared.Gifs;
using Content.Shared.Input;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.UserInterface.Systems.Chat.Widgets;

[GenerateTypedNameReferences]
[Virtual]
public partial class ChatBox : UIWidget, IEntityLinkClickHandler
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private ILogManager _log = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    private readonly ISawmill _sawmill;
    private readonly ChatUIController _controller;

    public bool Main { get; set; }

    public ChatSelectChannel SelectedChannel => ChatInput.ChannelSelector.SelectedChannel;

    public ChatBox()
    {
        RobustXamlLoader.Load(this);
        _sawmill = _log.GetSawmill("chat");

        ChatInput.Input.OnTextEntered += OnTextEntered;
        ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged += OnTextChanged;
        ChatInput.Input.OnFocusEnter += OnFocusEnter;
        ChatInput.Input.OnFocusExit += OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect += OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        ChatInput.FilterButton.Popup.OnGifFilter += OnGifFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights += OnNewHighlights;
        _controller = UserInterfaceManager.GetUIController<ChatUIController>();
        _controller.MessageAdded += OnMessageAdded;
        _controller.HighlightsUpdated += OnHighlightsUpdated;
        _controller.RegisterChat(this);
    }

    private void OnTextEntered(LineEditEventArgs args)
    {
        _controller.SendMessage(this, SelectedChannel);
    }

    private void OnMessageAdded(ChatMessage msg)
    {
        _sawmill.Debug($"{msg.Channel}: {msg.Message}");
        if (!ChatInput.FilterButton.Popup.IsActive(msg.Channel))
        {
            return;
        }

        if (msg is { Read: false, AudioPath: { } })
            _entManager.System<AudioSystem>().PlayGlobal(msg.AudioPath, Filter.Local(), false, AudioParams.Default.AddVolume(msg.AudioVolume));

        msg.Read = true;

        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();

        AddLine(msg.WrappedMessage, color);
    }

    private void OnHighlightsUpdated(string highlights)
    {
        ChatInput.FilterButton.Popup.UpdateHighlights(highlights);
    }

    private void OnChannelSelect(ChatSelectChannel channel)
    {
        _controller.UpdateSelectedChannel(this);
    }

    public void Repopulate()
    {
        Contents.Clear();

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }
    }

    /// <summary>
    /// Calls update function on every child <see cref="TextLinkLabel"/> in the ChatBox's OutputPanel "Contents"
    /// </summary>
    public void UpdateTextLinkLabelProperties(SharedChatSystem _sharedChatSys)
    {
        foreach (var contentsChild in Contents.Children)
        {
            if (contentsChild is TextLinkLabel textLinkLabel)
            {
                textLinkLabel.UpdateLabelProperties(_sharedChatSys);
            }
        }
    }

    // iss14: re-render history so existing GIF lines switch between inline image and plain text.
    private void OnGifFilter(bool show)
    {
        Repopulate();
    }

    private void OnChannelFilter(ChatChannel channel, bool active)
    {
        Contents.Clear();

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }

        if (active)
        {
            _controller.ClearUnfilteredUnreads(channel);
        }
    }

    private void OnNewHighlights(string highlighs)
    {
        _controller.UpdateHighlights(highlighs);
    }

    public void AddLine(string message, Color color)
    {
        // iss14: GIF lines carry an inline control taller than a text line; pad them so they get their own space.
        // With the "GIFs" filter off the tag is stripped and the line is shown as plain "[GIF] title" text.
        if (GifConstants.ContainsGifTag(message))
        {
            if (ChatInput.FilterButton.Popup.ShowGifs)
            {
                // Always start the GIF on its own line, regardless of how long the name/text before it is.
                message = message.Replace(" [gif ", "\n[gif ", StringComparison.Ordinal) + GifLinePadding();
            }
            else
                message = GifConstants.StripGifTags(message);
        }

        var formatted = new FormattedMessage(3);
        formatted.PushColor(color);
        formatted.AddMarkupOrThrow(message);
        formatted.Pop();
        Contents.AddMessage(formatted, tagsAllowed: null);
    }

    /// <summary>
    /// iss14: the engine's OutputPanel sizes an entry from font line heights only (RichTextEntry.Update), while an
    /// inline control taller than a line pushes the *following* lines down at draw time (controlYAdvance). So a GIF
    /// control at the end of a line would overlap the next entries. Appending k empty lines makes the entry tall
    /// enough. The GIF is placed on its own line (a newline is inserted before the tag), so with line height L and
    /// the GIF box B (both in px) the control's bottom is at ~L + B below the text; k = ceil((B - H) / L) + 1 empty
    /// lines after it (H = font height, plus one line of slack) always cover that.
    /// </summary>
    private string GifLinePadding()
    {
        var font = Contents.TryGetStyleProperty<Font>("font", out var styleFont)
            ? styleFont
            : UserInterfaceManager.ThemeDefaults.DefaultFont;

        var uiScale = Contents.UIScale > 0 ? Contents.UIScale : UIScale;
        if (uiScale <= 0)
            uiScale = 1f;

        var lineHeight = Math.Max(1, font.GetLineHeight(uiScale));
        var fontHeight = font.GetHeight(uiScale);
        var boxHeight = GifControl.BoxSize(_cfg).Y * uiScale;

        var lines = (int) Math.Ceiling((boxHeight - fontHeight) / lineHeight);
        lines = Math.Max(1, lines) + 1;
        return new string('\n', lines);
    }

    public void Focus(ChatSelectChannel? channel = null)
    {
        var input = ChatInput.Input;
        var selectStart = Index.End;

        if (channel != null)
            ChatInput.ChannelSelector.Select(channel.Value);

        input.IgnoreNext = true;
        input.GrabKeyboardFocus();

        input.CursorPosition = input.Text.Length;
        input.SelectionStart = selectStart.GetOffset(input.Text.Length);
    }

    public void CycleChatChannel(bool forward)
    {
        var idx = Array.IndexOf(ChannelSelectorPopup.ChannelSelectorOrder, SelectedChannel);
        do
        {
            // go over every channel until we find one we can actually select.
            idx += forward ? 1 : -1;
            idx = MathHelper.Mod(idx, ChannelSelectorPopup.ChannelSelectorOrder.Length);
        } while ((_controller.SelectableChannels & ChannelSelectorPopup.ChannelSelectorOrder[idx]) == 0);

        SafelySelectChannel(ChannelSelectorPopup.ChannelSelectorOrder[idx]);
    }

    public void SafelySelectChannel(ChatSelectChannel toSelect)
    {
        toSelect = _controller.MapLocalIfGhost(toSelect);
        if ((_controller.SelectableChannels & toSelect) == 0)
            return;

        ChatInput.ChannelSelector.Select(toSelect);
    }

    /// <summary>
    /// Sends a message to the server when this chat message is clicked.
    /// </summary>
    /// <param name="netEntity">Target entity of our event</param>
    public void HandleClick(NetEntity netEntity)
    {
        _entManager.RaisePredictiveEvent(new ChatLinkClickedRequestEvent(netEntity));
    }

    private void OnInputKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextReleaseFocus)
        {
            ChatInput.Input.ReleaseKeyboardFocus();
            ChatInput.Input.Clear();
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelForward)
        {
            CycleChatChannel(true);
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelBackward)
        {
            CycleChatChannel(false);
            args.Handle();
        }
    }

    private void OnTextChanged(LineEditEventArgs args)
    {
        // Update channel select button to correct channel if we have a prefix.
        _controller.UpdateSelectedChannel(this);

        // Warn typing indicator about change
        _controller.NotifyChatTextChange();
    }

    private void OnFocusEnter(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(true);
    }

    private void OnFocusExit(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(false);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing) return;
        _controller.UnregisterChat(this);
        ChatInput.Input.OnTextEntered -= OnTextEntered;
        ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged -= OnTextChanged;
        ChatInput.ChannelSelector.OnChannelSelect -= OnChannelSelect;
    }
}
