using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

/// <summary>Display state for the "New Life" ghost button, computed by <see cref="GhostUIController"/>.</summary>
public struct GhostNewLifeInfo
{
    /// <summary>Whether the button is shown at all (feature on for this player and lives remaining).</summary>
    public bool Show;
    /// <summary>Whether the button is clickable (eligible right now).</summary>
    public bool Enabled;
    /// <summary>Button label (countdown / lives remaining / blocked).</summary>
    public string Text;
}

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? NewLifePressed;
    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);
        NewLifeButton.OnPressed += _ => NewLifePressed?.Invoke();
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody, GhostNewLifeInfo newLife = default)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        UpdateNewLife(newLife);

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    /// <summary>iss14 fix: refresh only the New Life button (used by the per-second countdown tick).</summary>
    public void UpdateNewLife(GhostNewLifeInfo newLife)
    {
        NewLifeButton.Visible = newLife.Show;
        NewLifeButton.Disabled = !newLife.Enabled;
        if (newLife.Show)
            NewLifeButton.Text = newLife.Text;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
