// iss14: GIFs in chat via GifSnap
using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.GifConfig;

[GenerateTypedNameReferences]
public sealed partial class GifConfigWindow : FancyWindow
{
    public event Action<GifConfigField, string>? OnSet;

    private bool _updating;

    public GifConfigWindow()
    {
        RobustXamlLoader.Load(this);

        EnabledCheck.OnToggled += a => Set(GifConfigField.Enabled, a.Pressed.ToString());
        OocCheck.OnToggled += a => Set(GifConfigField.AllowOoc, a.Pressed.ToString());
        LoocCheck.OnToggled += a => Set(GifConfigField.AllowLooc, a.Pressed.ToString());

        // Commit on Enter and on click-away so typed values aren't lost.
        Bind(RequiredHoursEdit, GifConfigField.RequiredHours);
        Bind(SendCountEdit, GifConfigField.SendCount);
        Bind(SendPeriodEdit, GifConfigField.SendPeriod);
        Bind(SearchCountEdit, GifConfigField.SearchCount);
        Bind(SearchPeriodEdit, GifConfigField.SearchPeriod);
        Bind(FrameWidthEdit, GifConfigField.FrameWidth);
        Bind(FrameHeightEdit, GifConfigField.FrameHeight);
        Bind(MaxFramesEdit, GifConfigField.MaxFrames);
        Bind(MaxSheetBytesEdit, GifConfigField.MaxSheetBytes);
    }

    private void Bind(LineEdit edit, GifConfigField field)
    {
        edit.OnTextEntered += a => Set(field, a.Text);
        edit.OnFocusExit += a => Set(field, a.Text);
    }

    private void Set(GifConfigField field, string value)
    {
        if (!_updating)
            OnSet?.Invoke(field, value);
    }

    // Don't overwrite a field the user is currently editing.
    private static void SetText(LineEdit edit, string value)
    {
        if (!edit.HasKeyboardFocus())
            edit.Text = value;
    }

    public void SetState(GifConfigEuiState state)
    {
        _updating = true;

        EnabledCheck.Pressed = state.Enabled;
        OocCheck.Pressed = state.AllowOoc;
        LoocCheck.Pressed = state.AllowLooc;

        SetText(RequiredHoursEdit, state.RequiredHours.ToString("0.##", CultureInfo.InvariantCulture));
        SetText(SendCountEdit, state.SendCount.ToString(CultureInfo.InvariantCulture));
        SetText(SendPeriodEdit, state.SendPeriod.ToString("0.##", CultureInfo.InvariantCulture));
        SetText(SearchCountEdit, state.SearchCount.ToString(CultureInfo.InvariantCulture));
        SetText(SearchPeriodEdit, state.SearchPeriod.ToString("0.##", CultureInfo.InvariantCulture));
        SetText(FrameWidthEdit, state.FrameWidth.ToString(CultureInfo.InvariantCulture));
        SetText(FrameHeightEdit, state.FrameHeight.ToString(CultureInfo.InvariantCulture));
        SetText(MaxFramesEdit, state.MaxFrames.ToString(CultureInfo.InvariantCulture));
        SetText(MaxSheetBytesEdit, state.MaxSheetBytes.ToString(CultureInfo.InvariantCulture));

        RoleHintLabel.Text = state.RoleExists
            ? Loc.GetString("gif-config-role-hint")
            : Loc.GetString("gif-config-role-missing");

        EnabledCheck.Disabled = OocCheck.Disabled = LoocCheck.Disabled = !state.CanEdit;
        RequiredHoursEdit.Editable = state.CanEdit && state.RoleExists;
        SendCountEdit.Editable = SendPeriodEdit.Editable = SearchCountEdit.Editable = SearchPeriodEdit.Editable = state.CanEdit;
        FrameWidthEdit.Editable = FrameHeightEdit.Editable = MaxFramesEdit.Editable = MaxSheetBytesEdit.Editable = state.CanEdit;

        StatusLabel.Text = state.Status;

        _updating = false;
    }
}
