- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Elkridge
  - Marathon
  - Packed
  - Plasma
  - Exo
  - Snowball
  - Serpentcrest
  - Sushi
  - Tram2
- type: gameMapPool
  id: StanniMapPool
  maps:
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
  - Snowball
  - Serpentcrest
  - Sushi
  - Tram2
