// iss14: GIFs in chat via GifSnap
using System.IO;
using System.Numerics;
using Content.Client.Lobby;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Systems.Chat;
using Content.Shared.CCVar;
using Content.Shared.Chat;
using Content.Shared.Gifs;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Client.Gifs.UI;

/// <summary>
/// Search/trending GIF picker. Clicking a thumbnail asks the server to post that GIF to the chat box's current
/// channel (falling back to OOC when that channel doesn't take GIFs).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GifPickerWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IClyde _clyde = default!;
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private JobRequirementsManager _requirements = default!;
    [Dependency] private IClientPreferencesManager _preferences = default!;

    private const int ThumbnailSize = 96;

    private readonly GifClientSystem _gifs;
    private readonly ChatUIController _chat;
    private readonly List<OwnedTexture> _textures = new();

    private string _query = string.Empty;
    private int _page = 1;
    private bool _hasNext;
    private bool _waiting;

    public GifPickerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _gifs = _entMan.System<GifClientSystem>();
        _chat = UserInterfaceManager.GetUIController<ChatUIController>();

        SearchBox.OnTextEntered += _ => StartSearch(SearchBox.Text);
        SearchButton.OnPressed += _ => StartSearch(SearchBox.Text);
        PrevButton.OnPressed += _ => GoToPage(_page - 1);
        NextButton.OnPressed += _ => GoToPage(_page + 1);

        OnOpen += OnOpened;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _gifs.SearchResponse += OnSearchResponse;
        _gifs.Error += OnError;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _gifs.SearchResponse -= OnSearchResponse;
        _gifs.Error -= OnError;
    }

    private void OnOpened()
    {
        UpdateChannelLabel();
        UpdateRequirementStatus();

        // Trending on first open.
        if (ResultsGrid.ChildCount == 0 && !_waiting)
            StartSearch(string.Empty);
    }

    /// <summary>Channel the GIF will be posted to: the chat box's selection if it allows GIFs, otherwise OOC.</summary>
    private (ChatSelectChannel Channel, bool Fallback) ResolveChannel()
    {
        var allowed = GifConstants.ParseAllowedChannels(_cfg.GetCVar(CCVars.GifsAllowedChannels));
        var selected = _chat.GetSelectedChannel();
        if ((allowed & selected) != 0)
            return (selected, false);

        return (ChatSelectChannel.OOC, selected != ChatSelectChannel.OOC);
    }

    private void UpdateChannelLabel()
    {
        var (channel, fallback) = ResolveChannel();
        ChannelLabel.Text = fallback
            ? Loc.GetString("gifs-channel-fallback", ("channel", channel.ToString()))
            : Loc.GetString("gifs-channel-note", ("channel", channel.ToString()));
    }

    /// <summary>Tells the player up front if they don't meet the role-timer gate (the server checks for real).</summary>
    private void UpdateRequirementStatus()
    {
        var roleId = _cfg.GetCVar(CCVars.GifsRole);
        if (string.IsNullOrWhiteSpace(roleId) || !_proto.TryIndex<JobPrototype>(roleId, out var job))
            return;

        var profile = _preferences.Preferences?.SelectedCharacter as HumanoidCharacterProfile;
        if (_requirements.IsAllowed(job, profile, out var reason))
            return;

        StatusLabel.Text = Loc.GetString("gifs-status-requirements", ("reason", reason.ToString()));
    }

    private void StartSearch(string query)
    {
        _query = query.Trim();
        if (_query.Length > GifConstants.MaxQueryLength)
            _query = _query[..GifConstants.MaxQueryLength];
        GoToPage(1);
    }

    private void GoToPage(int page)
    {
        _page = Math.Clamp(page, 1, GifConstants.MaxPage);
        _waiting = true;
        StatusLabel.Text = Loc.GetString("gifs-status-searching");
        PrevButton.Disabled = true;
        NextButton.Disabled = true;
        _gifs.Search(_query, _page);
    }

    private void OnSearchResponse(GifSearchResponseEvent ev)
    {
        // Ignore stale responses from an earlier search.
        if (ev.Query != _query || ev.Page != _page)
            return;

        _waiting = false;
        _hasNext = ev.HasNext;
        PageLabel.Text = Loc.GetString("gifs-page", ("page", _page));
        PrevButton.Disabled = _page <= 1;
        NextButton.Disabled = !_hasNext;

        ClearResults();

        if (ev.Error != null)
        {
            StatusLabel.Text = Loc.GetString(ev.Error);
            return;
        }

        if (ev.Results.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("gifs-status-no-results");
            return;
        }

        StatusLabel.Text = _query.Length == 0
            ? Loc.GetString("gifs-status-trending")
            : Loc.GetString("gifs-status-results", ("count", ev.Results.Count));

        foreach (var entry in ev.Results)
            ResultsGrid.AddChild(MakeResultButton(entry));

        UpdateRequirementStatus();
    }

    private Control MakeResultButton(GifSearchEntry entry)
    {
        var button = new ContainerButton
        {
            StyleClasses = { ContainerButton.StyleClassButton },
            ToolTip = entry.Title,
            SetSize = new Vector2(ThumbnailSize + 8, ThumbnailSize + 8),
            Margin = new Thickness(2),
        };

        var texture = LoadThumbnail(entry);
        if (texture != null)
        {
            button.AddChild(new TextureRect
            {
                Texture = texture,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }
        else
        {
            button.AddChild(new Label
            {
                Text = entry.Title,
                ClipText = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }

        var id = entry.Id;
        button.OnPressed += _ => OnResultPressed(id);
        return button;
    }

    private OwnedTexture? LoadThumbnail(GifSearchEntry entry)
    {
        if (entry.ThumbnailPng.Length == 0)
            return null;

        try
        {
            using var stream = new MemoryStream(entry.ThumbnailPng, false);
            using var image = Image.Load<Rgba32>(stream);
            var texture = _clyde.LoadTextureFromImage(image, $"gif-thumb-{entry.Id}");
            _textures.Add(texture);
            return texture;
        }
        catch
        {
            return null;
        }
    }

    private void OnResultPressed(string id)
    {
        var (channel, _) = ResolveChannel();
        _gifs.Send(id, channel);
        StatusLabel.Text = Loc.GetString("gifs-status-sent");
        Close();
    }

    private void OnError(string locKey)
    {
        _waiting = false;
        StatusLabel.Text = Loc.GetString(locKey);
    }

    private void ClearResults()
    {
        ResultsGrid.RemoveAllChildren();
        foreach (var texture in _textures)
            texture.Dispose();
        _textures.Clear();
    }

    /// <summary>Releases thumbnail textures; called by the owning UI controller when the window is discarded.</summary>
    public void Cleanup()
    {
        ClearResults();
    }
}
