using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Access.UI;
using Content.Shared.Access;
using Content.Shared.Administration;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.IdPermissions;

/// <summary>
/// Admin version of the ID card console window: edits a specific ID card's name, job and access with no
/// privileged-ID restrictions and the full access-level list.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class IdPermissionsWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntitySystemManager _entitySystem = default!;

    private readonly SpriteSystem _spriteSystem;

    /// <summary>(fullName, jobTitle, jobProto (null = unchanged), jobIcon (null = unchanged), access)</summary>
    public event Action<string, string, string?, string?, List<ProtoId<AccessLevelPrototype>>>? OnWrite;

    private readonly AccessLevelControl _accessButtons = new();
    private readonly List<string> _jobPrototypeIds = new();
    private readonly Dictionary<string, TextureButton> _jobIconButtons = new();

    private string? _lastFullName;
    private string? _lastJobTitle;
    private string? _lastJobProto;
    private bool _updating;

    // The job that will be picked if the ID doesn't have a job on record.
    private static readonly ProtoId<JobPrototype> DefaultJob = "Passenger";

    public IdPermissionsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        FullNameLineEdit.OnTextEntered += _ => SubmitData();
        FullNameLineEdit.OnTextChanged += _ =>
        {
            FullNameSaveButton.Disabled = FullNameLineEdit.Text == _lastFullName;
        };
        FullNameSaveButton.OnPressed += _ => SubmitData();

        JobTitleLineEdit.OnTextEntered += _ => SubmitData();
        JobTitleLineEdit.OnTextChanged += _ =>
        {
            JobTitleSaveButton.Disabled = JobTitleLineEdit.Text == _lastJobTitle;
        };
        JobTitleSaveButton.OnPressed += _ => SubmitData();

        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>().ToList();
        jobs.Sort((x, y) => string.Compare(x.LocalizedName, y.LocalizedName, StringComparison.CurrentCulture));

        foreach (var job in jobs)
        {
            if (!job.OverrideConsoleVisibility.GetValueOrDefault(job.SetPreference))
                continue;

            _jobPrototypeIds.Add(job.ID);
            JobPresetOptionButton.AddItem(Loc.GetString(job.Name), _jobPrototypeIds.Count - 1);
        }

        SelectAllButton.OnPressed += _ =>
        {
            SetAllAccess(true);
            SubmitData();
        };

        DeselectAllButton.OnPressed += _ =>
        {
            SetAllAccess(false);
            SubmitData();
        };

        JobPresetOptionButton.OnItemSelected += SelectJobPreset;

        // Admin panel: offer every job icon that exists, including ones that have no job prototype
        // (syndicate, nuclear operatives, ERT, CBURN, death squad, ...).
        var jobIcons = _prototypeManager.EnumeratePrototypes<JobIconPrototype>()
            .OrderBy(i => i.ID, StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        foreach (var icon in jobIcons)
        {
            var iconButton = new TextureButton
            {
                TextureNormal = _spriteSystem.Frame0(icon.Icon),
                ToolTip = string.IsNullOrEmpty(icon.JobName) ? icon.ID : icon.LocalizedJobName,
                SetSize = new Vector2(24, 24),
            };

            iconButton.OnPressed += _ => SubmitData(icon.ID);

            JobIconGrid.AddChild(iconButton);
            _jobIconButtons.Add(icon.ID, iconButton);
        }

        // Admin panel: offer every access level that exists.
        var allAccess = _prototypeManager.EnumeratePrototypes<AccessLevelPrototype>()
            .OrderBy(a => a.GetAccessLevelName(), StringComparer.CurrentCultureIgnoreCase)
            .Select(a => new ProtoId<AccessLevelPrototype>(a.ID))
            .ToList();

        _accessButtons.Populate(allAccess, _prototypeManager);
        AccessLevelControlContainer.AddChild(_accessButtons);

        foreach (var button in _accessButtons.ButtonsList.Values)
        {
            button.OnPressed += _ => SubmitData();
        }
    }

    private void SetAllAccess(bool enabled)
    {
        foreach (var button in _accessButtons.ButtonsList.Values)
        {
            if (!button.Disabled && button.Pressed != enabled)
                button.Pressed = enabled;
        }
    }

    private void SelectJobPreset(OptionButton.ItemSelectedEventArgs args)
    {
        if (!_prototypeManager.TryIndex(_jobPrototypeIds[args.Id], out JobPrototype? job))
            return;

        JobTitleLineEdit.Text = Loc.GetString(job.Name);
        args.Button.SelectId(args.Id);

        SetAllAccess(false);

        foreach (var access in job.Access)
        {
            if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                button.Pressed = true;
        }

        foreach (var group in job.AccessGroups)
        {
            if (!_prototypeManager.Resolve(group, out AccessGroupPrototype? groupPrototype))
                continue;

            foreach (var access in groupPrototype.Tags)
            {
                if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                    button.Pressed = true;
            }
        }

        SubmitData();
    }

    public void UpdateState(IdPermissionsEuiState state)
    {
        _updating = true;

        TargetNameLabel.Text = state.TargetName;
        InvalidTargetLabel.Visible = !state.TargetValid;

        var enabled = state.CanEdit && state.TargetValid;

        var fullNameDirty = _lastFullName != null && FullNameLineEdit.Text != state.FullName;
        var jobTitleDirty = _lastJobTitle != null && JobTitleLineEdit.Text != state.JobTitle;

        FullNameLineEdit.Editable = enabled;
        if (!fullNameDirty)
            FullNameLineEdit.Text = state.FullName ?? string.Empty;
        FullNameSaveButton.Disabled = !enabled || !fullNameDirty;

        JobTitleLineEdit.Editable = enabled;
        if (!jobTitleDirty)
            JobTitleLineEdit.Text = state.JobTitle ?? string.Empty;
        JobTitleSaveButton.Disabled = !enabled || !jobTitleDirty;

        JobPresetOptionButton.Disabled = !enabled;
        SelectAllButton.Disabled = !enabled;
        DeselectAllButton.Disabled = !enabled;

        CurrentJobIconRect.Texture = _prototypeManager.TryIndex<JobIconPrototype>(state.JobIcon, out var currentIcon)
            ? _spriteSystem.Frame0(currentIcon.Icon)
            : null;

        foreach (var (iconId, iconButton) in _jobIconButtons)
        {
            iconButton.Disabled = !enabled;
            // Dim everything except the icon currently on the card.
            iconButton.Modulate = iconId == state.JobIcon ? Color.White : Color.White.WithAlpha(0.45f);
        }

        _accessButtons.UpdateState(state.Access,
            enabled ? _accessButtons.ButtonsList.Keys.ToList() : new List<ProtoId<AccessLevelPrototype>>());

        var jobIndex = _jobPrototypeIds.IndexOf(state.JobProto);
        if (jobIndex < 0)
            jobIndex = _jobPrototypeIds.IndexOf(DefaultJob);

        JobPresetOptionButton.SelectId(jobIndex);

        _lastFullName = state.FullName;
        _lastJobTitle = state.JobTitle;
        _lastJobProto = state.JobProto;

        _updating = false;
    }

    private void SubmitData(string? jobIcon = null)
    {
        if (_updating)
            return;

        // Only send the job preset when the admin actually changed it, like the ID card console.
        var jobProtoDirty = _lastJobProto != null
            && JobPresetOptionButton.SelectedId >= 0
            && JobPresetOptionButton.SelectedId < _jobPrototypeIds.Count
            && _jobPrototypeIds[JobPresetOptionButton.SelectedId] != _lastJobProto;

        OnWrite?.Invoke(
            FullNameLineEdit.Text,
            JobTitleLineEdit.Text,
            jobProtoDirty ? _jobPrototypeIds[JobPresetOptionButton.SelectedId] : null,
            jobIcon,
            _accessButtons.ButtonsList.Where(x => x.Value.Pressed).Select(x => x.Key).ToList());
    }
}
